EXTGW-574 Fix issue of resource dropdown box placeholder text
WSO2Telco/workflow-ui pull request #230
Opened 2020-11-20 13:29 UTC by sachindakumara

2020-11-20 16:09 UTC, chathurabuddi requested changes
Remove version changes from pom files

2020-11-23 03:52 UTC, chathurabuddi requested changes

2020-11-23 03:52 UTC, chathurabuddi commented on pom.xml
> +    <version>2.1.4-SNAPSHOT</version>
Fix this as well

2020-11-23 04:46 UTC, chathurabuddi approved these changes

2020-11-23 06:07 UTC, aushaniU approved these changes

2020-11-23 06:09 UTC, aushaniU commented
Merging the changes relevant to [EXTGW-574] Jira

2020-11-23 06:10 UTC, merged